<h1>helo man!!</h1>
<h2><?php echo $this->escapeHtml($this->getMessage()); ?></h2>
<h3>
	<?php 
		echo $this->escapeHtml($this->getTest()); 
	?>
</h3>

<h4><?php echo $this->escapeHtml($this->getName()); ?></h4>

<script type="text/javascript">
	var config = {
		path:{
			'hello': "Hanying_HelloWorld/jstest"
		}
	};

	requirejs(['jstest'], function(jstest) {
		alert("using js !!");
	});
	// alert("goes here");
</script>